### ISSUE TITLE
Pressing `c` in visual mode should delete currently selected characters

### ISSUE THREAD

**Issue by timkendrick** [brijeshb42/monaco-vim#1]
Amazing job on this! I've spotted one minor inconsistency so far:

**Steps to reproduce:**
1. Press `v` to enter visual mode
2. *[Optional]* Use motions to expand the selection
3. Press `c`

**Expected result:**
1. The currently selected range is deleted
2. The editor switches to insert mode, with the cursor at the start offset of the visual selection range

**Actual result:**
1. **[The selection is not deleted]**
2. The editor switches to insert mode, with the cursor at the start offset of the visual selection range

Great work though, it feels really solid otherwise!

**Comment by brijeshb42** [comment]
Same behavior with `d` works. Maybe some problem in the adapter. I'll look into it.

**Comment by timkendrick** [comment]
Wow, that was fast, thanks! The fix works great.

I've noticed another couple of small inconsistencies similar to this one, shall I submit issues for them? I don't want to deluge you with bug reports!

**Comment by timkendrick** [comment]
Sounds good – I'll have a bit more of a play around with it just to see if there's anything else that jumps out, but I should have a chance to write them up as a single ticket later today. Thanks again for all your great work on this!
