### ISSUE TITLE
Buggy on Safari.

### ISSUE THREAD

**Issue by hifall** [brijeshb42/monaco-vim#11]
I am using Safari 10.

I am unable to switch between normal/insert modes using ESC/i keys. To repro, simply load the official demo in Safari, and try to switch between modes.

**Comment by brijeshb42** [comment]
Just checked and its working fine. Do you have any extensions installed that manipulates keypresses like vimium in firefox?

**Comment by hifall** [comment]
No, I don't have any extension on my Safari. Although it's on an old version.
