### ISSUE TITLE
Visual mode breaks with "enter"

### ISSUE THREAD

**Issue by katlyn-edwards** [brijeshb42/monaco-vim#14]
Pressing enter while in visual mode should not actually insert an enter.

Repro steps: press 'v' to enter visual mode
select text using arrow keys. 
press enter. 
text is removed.

**Comment by katlyn-edwards** [comment]
Ideally you could mirror vi's behavior by letting enter select the next line. If that's not possible, I think not doing anything is preferrable to the current behavior.

**Comment by brijeshb42** [comment]
Above PR fixes this issue and somewhat fixes #15

**Comment by katlyn-edwards** [comment]
I think is is greatly improved! You're more than welcome to fix this if youw ant.
