### ISSUE TITLE
monaco-vim swallows Ctrl+C

### ISSUE THREAD

**Issue by katlyn-edwards** [brijeshb42/monaco-vim#18]
Cltr+C no longer copies to the clipboard with monaco-vim enabled. 
Repro-able with https://editor.bitwiser.in/

**Comment by brijeshb42** [comment]
What do you mean no longer? I don't think it did that ever.

**Comment by brijeshb42** [comment]
<kbd>CTRL + C</kbd> in vim goes back to normal mode. So I think its working as intended.

**Comment by brijeshb42** [comment]
This should now be possible using preventDefault

**Comment by katlyn-edwards** [comment]
I think this introduced a new issue: 
https://github.com/microsoft/azuredatastudio/blob/master/src/vs/editor/browser/controller/textAreaInput.ts#L135

Monaco itself is default preventing on ESC, so now you can't leave insert mode :C
