### ISSUE TITLE
preventDefault not respected

### ISSUE THREAD

**Issue by katlyn-edwards** [brijeshb42/monaco-vim#19]
related to https://github.com/brijeshb42/monaco-vim/issues/18

I added a listener for Ctrl+C to prevent sending it to monaco-vim; I added preventDefault, and stopPropagation, yet monaco-vim still handles it.

https://github.com/brijeshb42/monaco-vim/blob/0fb20c999a9d3115b9cdfcd336fcf64fd7cc5b7e/src/cm_adapter.js#L313

At this point, `e` should be checked ot see if `e.browserEvent.defaultPrevented`, and if so, do nothing.

**Comment by brijeshb42** [comment]
Fixed in `v0.0.14`.

**Comment by katlyn-edwards** [comment]
Thanks so much! Really appreciate all the work on this :]
