### ISSUE TITLE
Inconsistencies with CodeMirror vim

### ISSUE THREAD

**Issue by timkendrick** [brijeshb42/monaco-vim#2]
I've been playing around with the [demo](https://editor-a5ea1.firebaseapp.com/) and it's looking really good, I can't wait to use this in a real project!

I've spotted the following small issues – these all work fine in the [CodeMirror demo](https://codemirror.net/demo/vim) so hopefully they won't be too hard to fix. Let me know if you need further clarification on any of these.

---

- [x] Ctrl+O causes new line to be inserted

**Steps to reproduce:**
1. Press `}` to move to the next block
2. Press `Ctrl+O`

**Expected result:**
1. The cursor returns to the previous position

**Actual result:**
1. The cursor returns to the previous position
2. A new line is inserted at the cursor position

---

- [x] Parenthesis/brace text objects do not work

**Steps to reproduce:**
1. Position the cursor inside a pair of parentheses/braces (`(...)`, `{ ... }`, `[ ... ]` etc)
2. Press any of the corresponding text objects, e.g. `dib`, `vaB`, `ci]` etc

**Expected result:**
1. The edit/selection is applied

**Actual result:**
- No effect

N.B. More details on the available text objects can be found [here](http://vimdoc.sourceforge.net/htmldoc/motion.html#text-objects)

---

- [x] `t` jump cannot be repeated

**Steps to reproduce:**
1. Position the cursor at the start of a line that contains multiple occurrences of a character (e.g. `a`)
2. Press e.g. `ta` to jump to the position immediately before the first occurrence
3. Press `;` to jump to the next occurrence within the current line
4. Press `,` to jump back to the previous occurrence

**Expected result:**
- The cursor moves between occurrences within the current line

**Actual result:**
- The cursor stays at the first occurrence

N.B. This works fine with `f`, just not with `t`

---

- [x] Put does not cause cursor to change posittion

**Steps to reproduce:**
1. Position the cursor within a word
2. Press `ye` to yank the remainder of the word
3. Press `p` to put the yanked text after the current position

**Expected result:**
- The cursor moves to the end of the inserted text

**Actual result:**
- The cursor does not move

---

- [x] Delete > put > undo skips intermediate history state

**Steps to reproduce:**
1. Position the cursor within a word
2. Press `de` to delete the rest of the word
3. Press `p` to put the deleted text after the current position
4. Press `u` to undo the put

**Expected result:**
1. The inserted text is removed

**Actual result:**
1. The inserted text is removed
2. The deleted text is restored

---

- [x] `Ctrl+[` should perform the same function as `Esc` key

**Steps to reproduce:**
1. Press `i` to enter insert mode
2. Press `Ctrl+[`

**Expected result:**
- The editor leaves insert mode

**Actual result:**
- The editor remains in insert mode

---

… also one final one that is also present in the CodeMirror version – no worries if this is too much effort to look into!

- [ ] Change > undo creates extra intermediate history state

**Steps to reproduce:**
1. Press e.g. `s` to enter change mode (or `ce`, `ciw`, `vec` etc)
2. Type some text
3. Press `Esc` to leave insert mode
4. Press `u` to undo the insertion

**Expected result:**
1. The inserted text is removed
2. The deleted text is restored

**Actual result:**
1. The inserted text is removed
2. The deleted text is **not** restored unless you press `u` again

**Comment by brijeshb42** [comment]
The last one can't be fixed unless the extension maintains its own history. Others have been fixed

**Comment by timkendrick** [comment]
Thanks so much for looking into these! It's feeling really good. Although the brace/parenthesis text objects (e.g. `dib`, `ci]` etc) don't seem to be working in the demo, do you know why that might be?

**Comment by timkendrick** [comment]
Also on a very very minor note: after repeating a `t` search by pressing `;` several times, you should be able to skip back multiple times using `,`rather than just a single time. Same applies to `f`, which seems not to allow skipping back at all.

It appears this isn't actually supported by the CodeMirror version though so no bother if it's a non-trivial change.

**Comment by brijeshb42** [comment]
Found why bracket matching was not working. Other than that, any issues directly in Codemirror itself won't be fixed here. For those, a proper `VSCodeVim` like project needs to be there or it needs to be contributed directly to Codemirror itself.

**Comment by brijeshb42** [comment]
Closing it as no further issues are reported
