### ISSUE TITLE
Unable to integrate via AMD

### ISSUE THREAD

**Issue by jayakornk-bacon** [brijeshb42/monaco-vim#24]
Monaco Editor: v0.17.1
Monaco Vim: v0.0.14

I've tried an example code show how to integrate `monaco-vim`  with `monaco-editor` using AMD. But it has problem import some file.

Here is an error.
![image](https://user-images.githubusercontent.com/46859480/60528517-c9b25c80-9d1e-11e9-8b76-585be3cfbd9e.png)

This error comes from this file.
https://github.com/brijeshb42/monaco-vim/blob/1b58d92b6ca7ef15d9ccc4c70596f6ab6e573fb8/src/cm_adapter.js#L13

Could you help with this problem? I would love to use this ^^

Thank you

**Comment by brijeshb42** [comment]
Looking at the official demo, can you try loading it this way,

![Screenshot_20190702_235516](https://user-images.githubusercontent.com/717550/60536888-c99e6680-9cf6-11e9-9988-76dd27be737f.png)

Also add the path of monaco-vim in `paths`

**Comment by jayakornk** [comment]
I didn't install it locally but this solved the error though.
```
<script>
var require = { 
    paths: { 
        'vs': 'https://unpkg.com/monaco-editor/min/vs',
        'monaco-vim': 'https://unpkg.com/monaco-vim/dist/monaco-vim',
    }
};
</script>
<script src="https://unpkg.com/monaco-editor/min/vs/loader.js"></script>
<script src="https://unpkg.com/monaco-editor@0.17.1/min/vs/editor/editor.main.nls.js"></script>
<script src="https://unpkg.com/monaco-editor@0.17.1/min/vs/editor/editor.main.js"></script>
```

One more problem which I thought it cause by those error but it doesn't seem to be the case, I can't get out of **Insert Mode** using `<ESC>`.

**Comment by brijeshb42** [comment]
Are you using some keyboard related browser extension?

**Comment by jayakornk** [comment]
Nope, I tried in `Incognito Mode` to prevent any conflict with browser extensions.
