### ISSUE TITLE
Can't leave insert mode

### ISSUE THREAD

**Issue by katlyn-edwards** [brijeshb42/monaco-vim#27]
See https://github.com/brijeshb42/monaco-vim/issues/18

ESC is getting default-prevented from Monaco itself, and the library seems to be respecting that. 

Maybe we can add a flag/property to the event to disable defaultPrevented from stopping it?

**Comment by katlyn-edwards** [comment]
I ended updoing 
```
        Object.defineProperty(
            e, 'defaultPrevented', {writable: false, value: false});
```

**Comment by brijeshb42** [comment]
Introducing a flag seems the best way right know. At work, we are using monaco v0.14.x so we don't have this problem right now. But yeah, newer versions will need this. It would have been best if monaco also included a version number in their api like react does.

**Comment by ianberdin** [comment]
What we should with newer version?
Do we have a solution?

**Comment by brijeshb42** [comment]
Fixed with https://github.com/brijeshb42/monaco-vim/pull/28

Note that you won't be able to handle ESC key
