### ISSUE TITLE
Question about peerDependencies 

### ISSUE THREAD

**Issue by abirmingham** [brijeshb42/monaco-vim#35]
Greetings.

`monaco-vim` lists a peer dependency of `monaco-editor` at `"^0.14.0 || ^0.15.0"`, but `0.16` and `0.17` are available. Is `monaco-vim` incompatible with these newer versions of `monaco-editor`? If not, can we simply update the `peerDependencies` listing to include those newer versions? I'm happy to create a PR if so.

Thanks!

**Comment by brijeshb42** [comment]
Unless there is some breaking change in monaco api, this should work with any version of monaco. You can try locally if you want.
