### ISSUE TITLE
Actions on visual selection is off-by-one

### ISSUE THREAD

**Issue by katlyn-edwards** [brijeshb42/monaco-vim#44]
When selecting text in visual mode, the cursor position is off by one relative to regular vim.

Steps to reproduce:
(0) Enable vim keybindings on the demo site: https://editor.bitwiser.in/
(1) Enter the string "blah word blah" 
(2) Enter visual mode with the cursor over the "w" and move the cursor to be blinking over the "d". 
(3) Perform some operation on the selected text (e.g. delete (d), yank (y), toggle case (~))

Expected result:
The operation is performed on the string "word". For example, if you toggled case, the cell should contain "blah WORD blah".

Actual result:
The operation is performed on the string "wor". For example, if you toggled case, the cell contains "blah WORd blah".

This is different from vim's behavior in the terminal.

**Comment by brijeshb42** [comment]
Thanks for the report. I'll fix it this week.

**Comment by katlyn-edwards** [comment]
Hey there! Curious if there was any updates here? Thanks!
