### ISSUE TITLE
Bracket Matching 

### ISSUE THREAD

**Issue by rainke** [brijeshb42/monaco-vim#53]
when I put `vi(`, cursor is at `333`

it will match `{}` first, it's strange.

```js
function test(){
   console.log(333)
}
```

**Comment by rynorris** [comment]
Seems to be that the `scanForBracket` function ignores the `config.bracketRegex` argument and just scans for any brackets in the order `{([`.
https://github.com/brijeshb42/monaco-vim/blob/master/src/cm_adapter.js#L1062
