### ISSUE TITLE
Support newer monacos

### ISSUE THREAD

**Issue by mattgodbolt** [brijeshb42/monaco-vim#70]
We love this plugin; would be great if it supported 0.22.x monaco versions. It seems like it probably works, perhaps just the `package.json` peer dependencies need updating?

**Comment by CGNonofr** [comment]
This plugin does support monaco 0.22.x since https://github.com/brijeshb42/monaco-vim/pull/68

Indeed the package.json wasn't updated, but since it's only a peerDependency, it's shouldn't be blocking, is it?

**Comment by mattgodbolt** [comment]
Oh fabulous! I'ts not blocking, but it did make me think it wasn't "officially" ok :) Great news though, thanks!

**Comment by brijeshb42** [comment]
`package.json` was updated and new version `0.1.11` was released by the way just after the merge.

**Comment by mattgodbolt** [comment]
Thanks!
