### ISSUE TITLE
Some Vim scrolling keybindings are not working

### ISSUE THREAD

**Issue by dino-** [brijeshb42/monaco-vim#71]
In Vim mode, `<C-f>`, `<PageDown>`, `<C-b>`, `<PageUp>` aren't working for me in either Firefox or Chromium. These are keys I use a lot. I do see them defined in `monaco-vim/src/cm/keymap_vim.js`. Confirmed in the demo page at <https://editor.bitwiser.in/>. Am I doing something wrong?

**Comment by wujun51227** [comment]
fixed in new version
