### ISSUE TITLE
Compatibility with monaco 0.23.0

### ISSUE THREAD

**Issue by mattgodbolt** [brijeshb42/monaco-vim#73]
Monaco 0.23.0 is now out. Looks like it works, as best I can tell, but we get the warning on `npm install`.

**Comment by bandaloo** [comment]
i'd like to bump this too. i'm using monaco-vim for my project (great package, thanks!) and it would be nice to not have to use `--legacy-peer-deps` although i don't think it causes any real problems

**Comment by brijeshb42** [comment]
Done.
