### ISSUE TITLE
Mac Ctrl keybindings don't work

### ISSUE THREAD

**Issue by berniexie** [brijeshb42/monaco-vim#94]
Related to the two other issues: https://github.com/brijeshb42/monaco-vim/issues/92 and https://github.com/brijeshb42/monaco-vim/issues/91

But it's not just those two keybindings that don't work, none of the C-[key] bindings work. I've been able to trace the problem to the function `cmKeyToVimKey(key)` where in `Ctrl-[key]` combinations the key returns with the prefix 'Key' rather than the key itself. So for example, if I wanted to do `Ctrl-R` for undo, the key returned is `Ctrl-KeyR` rather than `Ctrl-R`, which gets misinterpreted when it is returned. 

To hack/fix the issue locally, I added this manipulation to the `pieces` array. However, not knowing the library intimately, I'm not sure this is a comprehensive enough fix? Any suggestions are welcome.

```
    if (lastPiece.startsWith("Key")) {
      pieces[pieces.length - 1] = lastPiece.substring(3).toLowerCase();
    }
```

**Comment by berniexie** [comment]
Upon further investigation, the `monacoToCmKey` function in cm_adapters is not anticipating keyName correctly anymore? If I change ` if (keyName.startsWith("KEY_")) {` to  `if (keyName.startsWith("Key")) {` on line 212 it works correctly again.

**Comment by CGNonofr** [comment]
I think monaco did change something related to it, see the fix on monaco-emacs: https://github.com/brijeshb42/monaco-emacs/pull/25/files

**Comment by brijeshb42** [comment]
Should work with 0.3.0
