### ISSUE TITLE
could newLineAndEnterInsertMode check for readOnly mode before it does anything?

### ISSUE THREAD

**Issue by karlili** [brijeshb42/monaco-vim#96]
In `enterInsertMode` (https://github.com/brijeshb42/monaco-vim/blob/master/src/cm/keymap_vim.js#L3446),  the function would check if the editor itself is currently in readOnly mode and if so, it will return immediately. 

Could we have the same check in the action `newLineAndEnterInsertMode` (https://github.com/brijeshb42/monaco-vim/blob/master/src/cm/keymap_vim.js#L3641), so that it toggles insert mode if and only if the editor is editable

**Comment by brijeshb42** [comment]
Is this behavior the same as in the Vim editor?
