### ISSUE TITLE
Global substitute command hangs when replacement string contains search string

### ISSUE THREAD

**Issue by Dumonu** [brijeshb42/monaco-vim#98]
## Reproduce Steps:
1. Ensure the open buffer contains some text: `foo`
2. Run a global substitute command where the search string is a substring of the replacement string: `:%s/foo/foobar/g`
## Expected:
`foo` becomes `foobar`
## Observed:
Editor hangs.

## Observed in:
- Bitburner v1.6.4 - https://github.com/danielyxie/bitburner
- Monaco Playground - https://editor.bitwiser.in/

**Comment by brijeshb42** [comment]
Tried this on the playground and it worked fine for me. Editor does not hang. Could you provide a reproducible url on maybe codesandbox.

**Comment by Dumonu** [comment]
Weird. I did my exact test and it didn't hang. But here's a series of steps that do:
1. Open Monaco Playground - https://editor.bitwiser.in/ - it shows a Kotlin code sample by default.
2. Enable Vim mode.
3. Run `:%s/kotlin/fookotlin/g`

I thought this would be much more consistent than it is.
